name: Compile examples

on:
  push:
    
jobs:
  arduino-devops:
    uses: Infineon/arduino-devops/.github/workflows/compile-examples.yml@compile-example-os-board-matrix
    with:
      ci-matrix-file-json: ci-build-matrix.json
      setup-script: bash ./tools/dev-setup.sh
    secrets: inherit