name: Release auto

on: 
  push:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
  
jobs:
  auto-tag:
    if:  ${{ github.event_name == 'workflow_dispatch' }}
    uses: Infineon/arduino-devops/.github/workflows/release-auto.yml@release-flow-auto
    with:
      version: ${{ inputs.version }}
    secrets: inherit

  release:
    needs: auto-tag
    uses: Infineon/arduino-devops/.github/workflows/release-core.yml@release-flow-auto
    with:
      release-title: arduino-core-psoc6
      setup-script: bash ./tools/dev-setup.sh
    secrets: inherit