name: Release auto

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
  
jobs:
  arduino-devops:
    uses: Infineon/arduino-devops/.github/workflows/release-auto.yml@release-flow-auto
    with:
      version: ${{ inputs.version }}
    secrets: inherit